// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTls returns the embedded CollectionSpec for tls.
func loadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tls: %w", err)
	}

	return spec, err
}

// loadTlsObjects loads tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsObjects
//	*tlsPrograms
//	*tlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsSpecs struct {
	tlsProgramSpecs
	tlsMapSpecs
	tlsVariableSpecs
}

// tlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsProgramSpecs struct {
	KprobeSockRecvmsg         *ebpf.ProgramSpec `ebpf:"kprobe_sock_recvmsg"`
	KprobeSockSendmsg         *ebpf.ProgramSpec `ebpf:"kprobe_sock_sendmsg"`
	ProbeEntrySslRead         *ebpf.ProgramSpec `ebpf:"probe_entry_ssl_read"`
	ProbeEntrySslWrite        *ebpf.ProgramSpec `ebpf:"probe_entry_ssl_write"`
	ProbeGnutlsRecordRecv     *ebpf.ProgramSpec `ebpf:"probe_gnutls_record_recv"`
	ProbeGnutlsRecordSend     *ebpf.ProgramSpec `ebpf:"probe_gnutls_record_send"`
	ProbeGoTlsRead            *ebpf.ProgramSpec `ebpf:"probe_go_tls_read"`
	ProbeGoTlsWrite           *ebpf.ProgramSpec `ebpf:"probe_go_tls_write"`
	ProbeReturnSslRead        *ebpf.ProgramSpec `ebpf:"probe_return_ssl_read"`
	ProbeReturnSslWrite       *ebpf.ProgramSpec `ebpf:"probe_return_ssl_write"`
	ProbeSslReadEx            *ebpf.ProgramSpec `ebpf:"probe_ssl_read_ex"`
	ProbeSslWriteEx           *ebpf.ProgramSpec `ebpf:"probe_ssl_write_ex"`
	TraceEnterConnect         *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
	TraceEnterRead            *ebpf.ProgramSpec `ebpf:"trace_enter_read"`
	TraceEnterRecvfrom        *ebpf.ProgramSpec `ebpf:"trace_enter_recvfrom"`
	TraceEnterRecvmsg         *ebpf.ProgramSpec `ebpf:"trace_enter_recvmsg"`
	TraceEnterSendmsg         *ebpf.ProgramSpec `ebpf:"trace_enter_sendmsg"`
	TraceEnterSendto          *ebpf.ProgramSpec `ebpf:"trace_enter_sendto"`
	TraceEnterSocket          *ebpf.ProgramSpec `ebpf:"trace_enter_socket"`
	TraceEnterWrite           *ebpf.ProgramSpec `ebpf:"trace_enter_write"`
	TraceExitAccept           *ebpf.ProgramSpec `ebpf:"trace_exit_accept"`
	TraceExitSocket           *ebpf.ProgramSpec `ebpf:"trace_exit_socket"`
	TraceTcpDataQueue         *ebpf.ProgramSpec `ebpf:"trace_tcp_data_queue"`
	TraceTcpPushPendingFrames *ebpf.ProgramSpec `ebpf:"trace_tcp_push_pending_frames"`
	TraceTcpRecvmsg           *ebpf.ProgramSpec `ebpf:"trace_tcp_recvmsg"`
	TraceTcpSendmsg           *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg"`
	TraceTcpWriteXmit         *ebpf.ProgramSpec `ebpf:"trace_tcp_write_xmit"`
}

// tlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsMapSpecs struct {
	ActiveSslSockets      *ebpf.MapSpec `ebpf:"active_ssl_sockets"`
	CurrentSslPtr         *ebpf.MapSpec `ebpf:"current_ssl_ptr"`
	FdToSockMap           *ebpf.MapSpec `ebpf:"fd_to_sock_map"`
	FilterConfig          *ebpf.MapSpec `ebpf:"filter_config"`
	PidFilter             *ebpf.MapSpec `ebpf:"pid_filter"`
	SockStorage           *ebpf.MapSpec `ebpf:"sock_storage"`
	SslOperationFlag      *ebpf.MapSpec `ebpf:"ssl_operation_flag"`
	SslOperationTimestamp *ebpf.MapSpec `ebpf:"ssl_operation_timestamp"`
	SslReadArgs           *ebpf.MapSpec `ebpf:"ssl_read_args"`
	SslWriteArgs          *ebpf.MapSpec `ebpf:"ssl_write_args"`
	Stats                 *ebpf.MapSpec `ebpf:"stats"`
	TlsEvents             *ebpf.MapSpec `ebpf:"tls_events"`
}

// tlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsVariableSpecs struct {
}

// tlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsObjects struct {
	tlsPrograms
	tlsMaps
	tlsVariables
}

func (o *tlsObjects) Close() error {
	return _TlsClose(
		&o.tlsPrograms,
		&o.tlsMaps,
	)
}

// tlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsMaps struct {
	ActiveSslSockets      *ebpf.Map `ebpf:"active_ssl_sockets"`
	CurrentSslPtr         *ebpf.Map `ebpf:"current_ssl_ptr"`
	FdToSockMap           *ebpf.Map `ebpf:"fd_to_sock_map"`
	FilterConfig          *ebpf.Map `ebpf:"filter_config"`
	PidFilter             *ebpf.Map `ebpf:"pid_filter"`
	SockStorage           *ebpf.Map `ebpf:"sock_storage"`
	SslOperationFlag      *ebpf.Map `ebpf:"ssl_operation_flag"`
	SslOperationTimestamp *ebpf.Map `ebpf:"ssl_operation_timestamp"`
	SslReadArgs           *ebpf.Map `ebpf:"ssl_read_args"`
	SslWriteArgs          *ebpf.Map `ebpf:"ssl_write_args"`
	Stats                 *ebpf.Map `ebpf:"stats"`
	TlsEvents             *ebpf.Map `ebpf:"tls_events"`
}

func (m *tlsMaps) Close() error {
	return _TlsClose(
		m.ActiveSslSockets,
		m.CurrentSslPtr,
		m.FdToSockMap,
		m.FilterConfig,
		m.PidFilter,
		m.SockStorage,
		m.SslOperationFlag,
		m.SslOperationTimestamp,
		m.SslReadArgs,
		m.SslWriteArgs,
		m.Stats,
		m.TlsEvents,
	)
}

// tlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsVariables struct {
}

// tlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPrograms struct {
	KprobeSockRecvmsg         *ebpf.Program `ebpf:"kprobe_sock_recvmsg"`
	KprobeSockSendmsg         *ebpf.Program `ebpf:"kprobe_sock_sendmsg"`
	ProbeEntrySslRead         *ebpf.Program `ebpf:"probe_entry_ssl_read"`
	ProbeEntrySslWrite        *ebpf.Program `ebpf:"probe_entry_ssl_write"`
	ProbeGnutlsRecordRecv     *ebpf.Program `ebpf:"probe_gnutls_record_recv"`
	ProbeGnutlsRecordSend     *ebpf.Program `ebpf:"probe_gnutls_record_send"`
	ProbeGoTlsRead            *ebpf.Program `ebpf:"probe_go_tls_read"`
	ProbeGoTlsWrite           *ebpf.Program `ebpf:"probe_go_tls_write"`
	ProbeReturnSslRead        *ebpf.Program `ebpf:"probe_return_ssl_read"`
	ProbeReturnSslWrite       *ebpf.Program `ebpf:"probe_return_ssl_write"`
	ProbeSslReadEx            *ebpf.Program `ebpf:"probe_ssl_read_ex"`
	ProbeSslWriteEx           *ebpf.Program `ebpf:"probe_ssl_write_ex"`
	TraceEnterConnect         *ebpf.Program `ebpf:"trace_enter_connect"`
	TraceEnterRead            *ebpf.Program `ebpf:"trace_enter_read"`
	TraceEnterRecvfrom        *ebpf.Program `ebpf:"trace_enter_recvfrom"`
	TraceEnterRecvmsg         *ebpf.Program `ebpf:"trace_enter_recvmsg"`
	TraceEnterSendmsg         *ebpf.Program `ebpf:"trace_enter_sendmsg"`
	TraceEnterSendto          *ebpf.Program `ebpf:"trace_enter_sendto"`
	TraceEnterSocket          *ebpf.Program `ebpf:"trace_enter_socket"`
	TraceEnterWrite           *ebpf.Program `ebpf:"trace_enter_write"`
	TraceExitAccept           *ebpf.Program `ebpf:"trace_exit_accept"`
	TraceExitSocket           *ebpf.Program `ebpf:"trace_exit_socket"`
	TraceTcpDataQueue         *ebpf.Program `ebpf:"trace_tcp_data_queue"`
	TraceTcpPushPendingFrames *ebpf.Program `ebpf:"trace_tcp_push_pending_frames"`
	TraceTcpRecvmsg           *ebpf.Program `ebpf:"trace_tcp_recvmsg"`
	TraceTcpSendmsg           *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
	TraceTcpWriteXmit         *ebpf.Program `ebpf:"trace_tcp_write_xmit"`
}

func (p *tlsPrograms) Close() error {
	return _TlsClose(
		p.KprobeSockRecvmsg,
		p.KprobeSockSendmsg,
		p.ProbeEntrySslRead,
		p.ProbeEntrySslWrite,
		p.ProbeGnutlsRecordRecv,
		p.ProbeGnutlsRecordSend,
		p.ProbeGoTlsRead,
		p.ProbeGoTlsWrite,
		p.ProbeReturnSslRead,
		p.ProbeReturnSslWrite,
		p.ProbeSslReadEx,
		p.ProbeSslWriteEx,
		p.TraceEnterConnect,
		p.TraceEnterRead,
		p.TraceEnterRecvfrom,
		p.TraceEnterRecvmsg,
		p.TraceEnterSendmsg,
		p.TraceEnterSendto,
		p.TraceEnterSocket,
		p.TraceEnterWrite,
		p.TraceExitAccept,
		p.TraceExitSocket,
		p.TraceTcpDataQueue,
		p.TraceTcpPushPendingFrames,
		p.TraceTcpRecvmsg,
		p.TraceTcpSendmsg,
		p.TraceTcpWriteXmit,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_x86_bpfel.o
var _TlsBytes []byte
